import { defaultMetadata } from "../utils/metadata";

export const metadata = defaultMetadata;

// export default function RootLayout({ children }) {
//   return (
//     <html lang="fr">
//       <body>{children}</body>
//     </html>
//   );
// }


// export const metadata = {
//   title: "FeexPay Dashboard",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
